#!/usr/bin/sh

sudo apt install libpam-pwdfile whois
sudo install -m 444 /dev/null /etc/localpasswd

if [ -f /etc/pam.d/gdm-password ]; then
    sudo sed -i '2iauth sufficient pam_pwdfile.so pwdfile=/etc/localpasswd' /etc/pam.d/gdm-password
elif [ -f /etc/pam.d/sddm ]; then
    sudo sed -i '2iauth sufficient pam_pwdfile.so pwdfile=/etc/localpasswd' /etc/pam.d/sddm
    sudo sed -i '4iauth sufficient pam_pwdfile.so pwdfile=/etc/localpasswd' /etc/pam.d/xscreensaver
else
    exit 1
fi

echo Restart to apply changes
